name: CrueKnight
favicon: null
layout_spectrum: 0.23692
typography_spectrum: 0.91282
title: A Crusader Knight.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#2e3842'
    - '#faf8fb'
    - '#5f7b87'
    - '#9ebcc6'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
