name: CrueKnight
favicon: null
layout_spectrum: 0.8460113650653511
typography_spectrum: 0.6290015326812863
title: A Crusader Knight.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06312606949359179
  lightness: 0.3278129177633673
  saturation: 0.3336800264660269
  rhythmicContrast: 0.32614996028132737
purpose: []
