typography_spectrum: 0.38679275405593216
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.8011411202605814
  lightness: 0.5200086208060384
  saturation: 0.8974380779545754
  rhythmicContrast: 0.8135230303741992
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5874319209251553
analytics:
  google: null
  facebook: null
  twitter: null
name: CrueKnight
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The New Site of a New Human
    id: 2bdcf43e-aa7c-4c0c-b5a7-352af412cabc
    type: content
  - name: About me.
    id: d1306323-bfea-46bc-8e1d-24fd4d38a683
    type: content
favicon: null
title: A Crusader Knight.
description: 100% Organic.
purpose: []
