typography_spectrum: 0.38679275405593216
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.8011411202605814
  lightness: 0.5200086208060384
  saturation: 0.8974380779545754
  rhythmicContrast: 0.8135230303741992
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5874319209251553
analytics:
  google: null
  facebook: null
  twitter: null
name: CrueKnight
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A Crusader Knight.
description: 100% Organic.
purpose: []
